-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 22:33:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema immbodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema immbodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `immbodb` DEFAULT CHARACTER SET utf8 ;
USE `immbodb` ;

-- -----------------------------------------------------
-- Table `immbodb`.`ParametroInmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`ParametroInmueble` (
  `idParametroInmueble` INT NOT NULL,
  `nombreParametroInmueble` VARCHAR(45) NOT NULL,
  `valorParametroInmueble` VARCHAR(45) NOT NULL,
  `descripcionParametroInmueble` VARCHAR(255) NULL,
  `m2MinimoParametroInmueble` INT NULL,
  PRIMARY KEY (`idParametroInmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`TipoProyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`TipoProyecto` (
  `idTipoProyecto` INT NOT NULL,
  `nombreTipoProyecto` VARCHAR(45) NULL,
  `descripTipoProyecto` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Etapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Etapa` (
  `idEtapa` INT NOT NULL,
  `nombreEtapa` VARCHAR(45) NOT NULL,
  `descripcionEtapa` VARCHAR(255) NULL,
  `noTipoImmuebleEtapa` INT NULL,
  `noTipoImmueble2Etapa` INT NULL,
  `TipoProyecto_idTipoProyecto` INT NOT NULL,
  PRIMARY KEY (`idEtapa`, `TipoProyecto_idTipoProyecto`),
  INDEX `fk_Etapa_TipoProyecto1_idx` (`TipoProyecto_idTipoProyecto` ASC),
  CONSTRAINT `fk_Etapa_TipoProyecto1`
    FOREIGN KEY (`TipoProyecto_idTipoProyecto`)
    REFERENCES `immbodb`.`TipoProyecto` (`idTipoProyecto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
COMMENT = 'colEtapa';


-- -----------------------------------------------------
-- Table `immbodb`.`TipoInmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`TipoInmueble` (
  `idTipoInmueble` INT NOT NULL,
  `areaTipoInmueble` INT NOT NULL,
  `noUnidadesTipoInmueble` INT NOT NULL,
  `valorM2TipoInmueble` DECIMAL(13,4) NOT NULL,
  `secundarioTipoInmueble` TINYINT NOT NULL,
  `ParametroInmueble_idParametroInmueble` INT NOT NULL,
  `valorSalariosMinTipoInmueble` DECIMAL(7,2) NULL,
  `Etapa_idEtapa` INT NOT NULL,
  `Etapa_TipoProyecto_idTipoProyecto` INT NOT NULL,
  PRIMARY KEY (`idTipoInmueble`, `ParametroInmueble_idParametroInmueble`, `Etapa_idEtapa`, `Etapa_TipoProyecto_idTipoProyecto`),
  INDEX `fk_TipoInmueble_ParametroInmueble1_idx` (`ParametroInmueble_idParametroInmueble` ASC),
  INDEX `fk_TipoInmueble_Etapa1_idx` (`Etapa_idEtapa` ASC, `Etapa_TipoProyecto_idTipoProyecto` ASC),
  CONSTRAINT `fk_TipoInmueble_ParametroInmueble1`
    FOREIGN KEY (`ParametroInmueble_idParametroInmueble`)
    REFERENCES `immbodb`.`ParametroInmueble` (`idParametroInmueble`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_TipoInmueble_Etapa1`
    FOREIGN KEY (`Etapa_idEtapa` , `Etapa_TipoProyecto_idTipoProyecto`)
    REFERENCES `immbodb`.`Etapa` (`idEtapa` , `TipoProyecto_idTipoProyecto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Lote` (
  `idLote` INT NOT NULL,
  `areaBrutaLote` DECIMAL(8,3) NOT NULL,
  `areaCesionViasLote` DECIMAL(8,3) NULL,
  `porcentajeCesionVerdesLote` DECIMAL(5,2) NULL,
  `areaCesionTierraLote` DECIMAL(4,2) NULL,
  `valorM2Cesion` DECIMAL(13,4) NULL,
  `valorLote` DECIMAL(13,4) NULL,
  `valorPorcentajeLote` DECIMAL(5,2) NULL,
  `porcentajeFinanciarLote` DECIMAL(5,2) NULL,
  `mesesGraciaIntLote` INT NULL,
  `tasaInterésMensualLote` DECIMAL(5,2) NULL,
  `mesesTotalesPagoLote` INT NOT NULL,
  `valorTotalLote` DECIMAL(13,4) NULL,
  `mesesDePagoLote` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Macroproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Macroproyecto` (
  `idMacroproyecto` INT NOT NULL,
  `nombreMacroproyecto` VARCHAR(45) NOT NULL,
  `descMacroproyecto` VARCHAR(255) NULL,
  `m2Macroproyecto` INT NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idMacroproyecto`, `Lote_idLote`),
  INDEX `fk_Macroproyecto_Lote1_idx` (`Lote_idLote` ASC),
  CONSTRAINT `fk_Macroproyecto_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `immbodb`.`Lote` (`idLote`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Proyecto` (
  `idProyecto` INT NOT NULL,
  `nombreProyecto` VARCHAR(255) NULL,
  `Macroproyecto_idMacroproyecto` INT NOT NULL,
  `Macroproyecto_Lote_idLote` INT NOT NULL,
  `m2PorProyecto` INT NOT NULL,
  `descripcionProyecto` VARCHAR(255) NULL,
  PRIMARY KEY (`idProyecto`, `Macroproyecto_idMacroproyecto`, `Macroproyecto_Lote_idLote`),
  INDEX `fk_Proyecto_Macroproyecto1_idx` (`Macroproyecto_idMacroproyecto` ASC, `Macroproyecto_Lote_idLote` ASC),
  CONSTRAINT `fk_Proyecto_Macroproyecto1`
    FOREIGN KEY (`Macroproyecto_idMacroproyecto` , `Macroproyecto_Lote_idLote`)
    REFERENCES `immbodb`.`Macroproyecto` (`idMacroproyecto` , `Lote_idLote`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Inmueble` (
  `idInmueble` INT NOT NULL,
  PRIMARY KEY (`idInmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`TipoIncremento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`TipoIncremento` (
  `idTipoIncremento` INT NOT NULL,
  `tipoIncremento` INT NOT NULL COMMENT '1 unidades\n2 meses\n',
  `valorIncrTipoIncremento` INT NULL COMMENT 'Valor del incremento\n',
  PRIMARY KEY (`idTipoIncremento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Incremento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Incremento` (
  `idIncremento` INT NOT NULL,
  `numerodeIncremento` INT NOT NULL,
  `porReajusteFactorIncremento` DECIMAL(5,2) NOT NULL,
  `TipoIncremento_idTipoIncremento` INT NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Proyecto_Lote_idLote` INT NOT NULL,
  `porcTopeReajusteIncremento` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idIncremento`, `TipoIncremento_idTipoIncremento`, `Proyecto_idProyecto`, `Proyecto_Lote_idLote`),
  INDEX `fk_Incremento_TipoIncremento1_idx` (`TipoIncremento_idTipoIncremento` ASC),
  INDEX `fk_Incremento_Proyecto1_idx` (`Proyecto_idProyecto` ASC, `Proyecto_Lote_idLote` ASC),
  CONSTRAINT `fk_Incremento_TipoIncremento1`
    FOREIGN KEY (`TipoIncremento_idTipoIncremento`)
    REFERENCES `immbodb`.`TipoIncremento` (`idTipoIncremento`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Incremento_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `immbodb`.`Proyecto` (`idProyecto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Venta` (
  `idVentas` INT NOT NULL,
  `velocidadVentas` INT NOT NULL,
  `porcentajeTopeRemanenteVentas` DECIMAL(5,2) NULL,
  `velocidadUltimasVentas` INT NULL,
  `porcTopeInicialVentas` DECIMAL(5,2) NULL,
  `porcVelInicialVentas` DECIMAL(5,2) NULL,
  `fechaInicioVentas` DATETIME NOT NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Proyecto_Lote_idLote` INT NOT NULL,
  `volumenTotalVenta` DECIMAL(13,4) NULL,
  `reajusteVenta` DECIMAL(13,4) NULL,
  `volumenInicialesVenta` DECIMAL(13,4) NULL COMMENT 'Volumen ventas iniciales\n',
  PRIMARY KEY (`idVentas`, `Proyecto_idProyecto`, `Proyecto_Lote_idLote`),
  INDEX `fk_Ventas_Proyecto1_idx` (`Proyecto_idProyecto` ASC, `Proyecto_Lote_idLote` ASC),
  CONSTRAINT `fk_Ventas_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `immbodb`.`Proyecto` (`idProyecto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`PagoLote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`PagoLote` (
  `idPagoLote` INT NOT NULL,
  `mesPagoLote` INT NULL,
  `porcentajeMesPagoLote` DECIMAL(5,2) NULL,
  `Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idPagoLote`, `Lote_idLote`),
  INDEX `fk_PagoLote_Lote1_idx` (`Lote_idLote` ASC),
  CONSTRAINT `fk_PagoLote_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `immbodb`.`Lote` (`idLote`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`ProyeccionIPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`ProyeccionIPC` (
  `idProyeccionIPC` INT NOT NULL,
  `añosProyeccionIPC` INT NOT NULL,
  `tasaBaseProyeccionIPC` DECIMAL(5,2) NULL,
  `Proyecto_idProyecto` INT NOT NULL,
  `Proyecto_Lote_idLote` INT NOT NULL,
  PRIMARY KEY (`idProyeccionIPC`, `Proyecto_idProyecto`, `Proyecto_Lote_idLote`),
  INDEX `fk_ProyeccionIPC_Proyecto1_idx` (`Proyecto_idProyecto` ASC, `Proyecto_Lote_idLote` ASC),
  CONSTRAINT `fk_ProyeccionIPC_Proyecto1`
    FOREIGN KEY (`Proyecto_idProyecto`)
    REFERENCES `immbodb`.`Proyecto` (`idProyecto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`TablaIPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`TablaIPC` (
  `idTablaIPCs` INT NOT NULL,
  `anoTablaIPCs` INT NULL,
  `ipcAnoTablaIPCs` DECIMAL(5,2) NULL,
  `noImueblesEntregadoTablaIPCs` INT NULL,
  `ProyeccionIPC_idProyeccionIPC` INT NOT NULL,
  PRIMARY KEY (`idTablaIPCs`, `ProyeccionIPC_idProyeccionIPC`),
  INDEX `fk_TablaIPCs_ProyeccionIPC1_idx` (`ProyeccionIPC_idProyeccionIPC` ASC),
  CONSTRAINT `fk_TablaIPCs_ProyeccionIPC1`
    FOREIGN KEY (`ProyeccionIPC_idProyeccionIPC`)
    REFERENCES `immbodb`.`ProyeccionIPC` (`idProyeccionIPC`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`Parametros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`Parametros` (
  `idParametros` INT NOT NULL,
  `nombreParametros` VARCHAR(45) NOT NULL,
  `descripcionParametros` VARCHAR(255) NULL,
  `valorParametros` VARCHAR(45) NULL,
  PRIMARY KEY (`idParametros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `immbodb`.`SubEtapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `immbodb`.`SubEtapa` (
  `idSubEtapa` INT NOT NULL,
  `nombreSubEtapa` VARCHAR(45) NULL,
  `descripcionSubEtapa` VARCHAR(255) NULL,
  `Etapa_idEtapa` INT NOT NULL,
  PRIMARY KEY (`idSubEtapa`, `Etapa_idEtapa`),
  INDEX `fk_SubEtapa_Etapa1_idx` (`Etapa_idEtapa` ASC),
  CONSTRAINT `fk_SubEtapa_Etapa1`
    FOREIGN KEY (`Etapa_idEtapa`)
    REFERENCES `immbodb`.`Etapa` (`idEtapa`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

CREATE USER 'factiUser' IDENTIFIED BY 'factiUser2017';

GRANT ALL ON `immbodb`.* TO 'factiUser';
GRANT SELECT ON TABLE `immbodb`.* TO 'factiUser';
GRANT SELECT, INSERT, TRIGGER ON TABLE `immbodb`.* TO 'factiUser';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `immbodb`.* TO 'factiUser';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
